export const siteConfig = {
  businessName: "Neon Web Agency",
  tagline: "Ottawa's Premier Web Design Agency",
  keyword: "Web Design Ottawa",
  city: "Ottawa",
  province: "Ontario",
  country: "CA",
  postalCode: "K1A 0A1",
  streetAddress: "123 Sparks Street",
  phone: "(613) 558-3577",
  email: "info@neonmediapro.org",
  website: "https://neoncraft.me",
  author: {
    name: "Bilal Moussa",
    title: "Founder & Lead Developer",
    bio: "Bilal Moussa is the founder and lead developer at Neon Web Agency, with over 10 years of experience building high-performance websites and SEO strategies for Ottawa businesses.",
  },
  foundingYear: 2018,
  priceRange: "$$",
  logoUrl: "/logo.png",
  seoTitle: "Web Design Ottawa | Websites That Convert - Neon Web Agency",
  seoDescription: "Ottawa's top-rated web design agency. We build fast, mobile-first websites for small businesses that rank on Google and convert visitors into customers.",
  ogImage: "/og-image.jpg",
  ratings: {
    ratingValue: "4.9",
    reviewCount: "87",
    bestRating: "5",
  },
  hero: {
    headline: "Web Design Ottawa",
    subheadline: "We build stunning, high-performance websites that help Ottawa businesses attract more customers, rank higher on Google, and grow online.",
    heroSuffix: "That Drives Real Results",
    ctaText: "Book a Free Strategy Call",
    ctaLink: "https://calendly.com/neonmedia/strategy-call",
    secondaryCtaText: "View Our Work",
    secondaryCtaLink: "#portfolio",
    stats: [
      { value: "150+", label: "Websites Launched" },
      { value: "98%", label: "Client Satisfaction" },
      { value: "4.9★", label: "Google Rating" },
      { value: "10+", label: "Years Experience" },
    ],
  },
  trustBar: {
    heading: "Trusted by Ottawa Businesses",
    logos: [
      { name: "Rideau Dental Clinic", initial: "RD" },
      { name: "Capital City Plumbing", initial: "CC" },
      { name: "Byward Market Bistro", initial: "BM" },
      { name: "Ottawa Legal Associates", initial: "OL" },
      { name: "Glebe Fitness Studio", initial: "GF" },
      { name: "Kanata Tech Solutions", initial: "KT" },
    ],
  },
  intro: {
    heading: "Ottawa Small Business Website Design That Drives Results",
    paragraphs: [
      "Your website is your most powerful sales tool. In today's digital-first world, Ottawa businesses need more than just an online presence — they need a website that works as hard as they do. At Neon Web Agency, we specialize in web design in Ottawa for small businesses, creating custom websites that look exceptional, load fast, and convert visitors into paying customers.",
      "Whether you're a local restaurant on Elgin Street, a professional service firm in the ByWard Market, a contractor in Kanata, or a retail shop in Westboro, our Ottawa web design team understands the local market inside and out.",
      "Every website we build is mobile-responsive, optimized for search engines, and designed with your specific business goals in mind. No templates. No cookie-cutter solutions. Just custom web design Ottawa businesses trust to grow their revenue.",
      "With over 150 websites launched for businesses across the National Capital Region, we've helped companies in every industry achieve measurable growth through professional web design.",
    ],
  },
  services: [
    { title: "Custom Website Design", description: "Unique, brand-aligned website designs built from scratch for Ottawa businesses. No templates — every pixel is crafted to reflect your brand identity and convert visitors into customers.", icon: "palette", slug: "web-design" },
    { title: "Responsive Web Development", description: "Websites that look and perform flawlessly on every device — desktop, tablet, and mobile. Built with clean, modern code for lightning-fast load times under 2 seconds.", icon: "devices", slug: "responsive-development" },
    { title: "Local SEO Optimization", description: "Rank higher on Google for Ottawa-based searches. We optimize every page with local SEO best practices, Google Business Profile setup, and citation building.", icon: "search", slug: "seo" },
    { title: "E-Commerce Solutions", description: "Sell products online with a custom e-commerce store built for Ottawa businesses. Secure payments, inventory management, and seamless shopping experience.", icon: "cart", slug: "ecommerce" },
    { title: "Website Maintenance & Support", description: "Keep your website secure, updated, and running smoothly with our ongoing maintenance packages starting at $99/month.", icon: "shield", slug: "website-maintenance" },
    { title: "Content Management Systems", description: "Easily update your own website content with user-friendly CMS platforms. We build sites that empower Ottawa business owners to make changes without coding.", icon: "edit", slug: "cms" },
    { title: "Landing Page & Funnel Design", description: "High-converting landing pages designed to capture leads and drive sales for your Ottawa business.", icon: "target", slug: "landing-pages" },
  ],
  process: {
    heading: "Our Proven Web Design Process",
    subheading: "From first call to launch day, here's how we build websites that deliver results for Ottawa businesses.",
    steps: [
      { number: "01", title: "Discovery & Strategy", description: "We start with a free strategy call to understand your business, goals, target audience, and competitors in the Ottawa market." },
      { number: "02", title: "Design & Wireframing", description: "Our designers create custom mockups and wireframes tailored to your brand. You'll see exactly how your website will look before we write a single line of code." },
      { number: "03", title: "Development & SEO", description: "We build your website with clean, modern code optimized for speed and search engines. Every page is crafted with on-page SEO and local Ottawa keywords." },
      { number: "04", title: "Testing & QA", description: "Before launch, we rigorously test across all devices, browsers, and screen sizes. We check load speed, SEO elements, forms, and functionality." },
      { number: "05", title: "Launch & Growth", description: "We launch your new website, set up Google Analytics and Search Console, submit your sitemap, and provide ongoing support." },
    ],
  },
  portfolio: [
    { title: "Rideau Dental Clinic", category: "Healthcare", description: "Complete website redesign with online booking integration. New patient inquiries increased 180% within 90 days.", results: "+180% new patient leads" },
    { title: "Capital City Plumbing", category: "Home Services", description: "Mobile-first website with emergency service booking. Now ranking #1 on Google for 'plumber Ottawa'.", results: "#1 Google ranking" },
    { title: "Byward Market Bistro", category: "Restaurant", description: "Modern restaurant website with integrated online ordering. Online orders increased 250%.", results: "+250% online orders" },
    { title: "Ottawa Legal Associates", category: "Professional Services", description: "Authority-building website with case study library. Consultation requests doubled within 90 days.", results: "2x consultations in 90 days" },
    { title: "Glebe Fitness Studio", category: "Fitness", description: "Dynamic fitness website with class scheduling and membership portal. Membership sign-ups increased 120%.", results: "+120% membership sign-ups" },
    { title: "Kanata Tech Solutions", category: "Technology", description: "B2B lead generation website with detailed case studies. Generates 50+ qualified leads every month.", results: "50+ leads per month" },
  ],
  testimonials: [
    { name: "Sarah Mitchell", business: "Rideau Dental Clinic", role: "Practice Manager", quote: "Neon Web Agency completely transformed our online presence. Our new website is beautiful, fast, and brings in new patients every single week.", rating: 5 },
    { name: "James Rodriguez", business: "Capital City Plumbing", role: "Owner", quote: "Within 3 months of launching our new site, we went from page 3 to the #1 spot on Google. The phone hasn't stopped ringing since.", rating: 5 },
    { name: "Emily Chen", business: "Byward Market Bistro", role: "General Manager", quote: "The team at Neon Web Agency understood exactly what we needed. Our online ordering system works flawlessly and revenue from online orders tripled.", rating: 5 },
    { name: "David Thompson", business: "Ottawa Legal Associates", role: "Managing Partner", quote: "Professional, responsive, and detail-oriented. We've seen a significant increase in consultation requests.", rating: 5 },
    { name: "Lisa Patel", business: "Glebe Fitness Studio", role: "Founder", quote: "Our old website was embarrassing. Neon Web Agency designed something we're truly proud of — and our membership sign-ups prove it works.", rating: 5 },
  ],
  pricing: {
    heading: "Transparent Web Design Pricing in Ottawa",
    subheading: "No hidden fees. No surprises. Honest web design pricing for Ottawa businesses of every size.",
    plans: [
      { name: "Starter", price: "$1,499", description: "Perfect for new Ottawa businesses that need a professional online presence.", features: ["Up to 5 custom pages", "Mobile-responsive design", "Basic SEO setup", "Contact form integration", "1 round of revisions", "Google Analytics setup", "2 weeks delivery"], popular: false },
      { name: "Growth", price: "$3,499", description: "For established Ottawa businesses ready to dominate their local market.", features: ["Up to 10 custom pages", "Mobile-responsive design", "Advanced local SEO", "CMS integration (WordPress)", "Blog setup", "3 rounds of revisions", "Speed optimization (<2s load)", "Google Business Profile setup", "3 weeks delivery"], popular: true },
      { name: "Premium", price: "$6,999", description: "Full-scale web design solution for maximum impact and ongoing growth.", features: ["Unlimited pages", "Custom animations & interactions", "Full SEO strategy & execution", "E-commerce ready", "CMS + blog + portfolio", "Unlimited revisions", "Priority support (24h response)", "Monthly analytics reports", "4 weeks delivery"], popular: false },
    ],
  },
  faq: [
    { question: "How much does web design cost in Ottawa?", answer: "Our web design packages in Ottawa start at $1,499 for a professional 5-page website. Most Ottawa small businesses invest between $1,499 and $6,999 for a custom website." },
    { question: "How long does it take to build a website?", answer: "Most websites are completed within 2-4 weeks, depending on the project scope." },
    { question: "Do you offer website maintenance and support?", answer: "Yes! We offer ongoing website maintenance packages starting at $99/month including security updates, performance monitoring, and priority support." },
    { question: "Will my website be optimized for mobile devices?", answer: "Absolutely. Every website we build is fully responsive and mobile-first. Over 60% of Ottawa web traffic comes from mobile devices." },
    { question: "Can you help my Ottawa business rank on Google?", answer: "Yes, SEO is built into every website we create including optimized meta tags, schema markup, fast loading speeds, and local SEO optimization." },
    { question: "Do I need to provide content for my website?", answer: "We can work with whatever you have. We also offer professional copywriting services optimized for SEO and your Ottawa target audience." },
    { question: "What platform do you use to build websites?", answer: "We use modern web technologies including Next.js, React, and WordPress depending on your specific needs and budget." },
    { question: "Why should I choose Neon Web Agency?", answer: "We combine stunning design with proven marketing strategy. 98% client satisfaction rate, 150+ successful website launches, and a 4.9-star Google rating." },
  ],
  cta: {
    heading: "Ready to Invest in Professional Web Design?",
    subheading: "Book a free 30-minute website strategy call. We'll audit your current site, discuss your goals, and create a custom plan.",
    buttonText: "Book a Free Strategy Call",
    buttonLink: "https://calendly.com/neonmedia/strategy-call",
    features: ["Free website audit", "Custom growth strategy", "No obligation", "30-minute call"],
  },
  areas: [
    { name: "Ottawa", slug: "ottawa", description: "Custom web design for businesses in Ottawa's downtown core, including the ByWard Market, Centretown, and the Glebe." },
    { name: "Kanata", slug: "kanata", description: "Website design for Kanata's thriving tech sector and local businesses." },
    { name: "Barrhaven", slug: "barrhaven", description: "Professional web design for Barrhaven's growing community of small businesses." },
    { name: "Orleans", slug: "orleans", description: "Web design services for Orleans businesses in Ottawa's east end." },
    { name: "Nepean", slug: "nepean", description: "Custom websites for Nepean businesses along Merivale Road and Bells Corners." },
    { name: "Gloucester", slug: "gloucester", description: "Responsive web design for Gloucester businesses along Ogilvie and Blair Road." },
    { name: "Gatineau", slug: "gatineau", description: "Bilingual web design for businesses in Gatineau and the Quebec side of the NCR." },
  ],
  navigation: {
    main: [
      { label: "Services", href: "/services/" },
      { label: "Industries", href: "/industries/", children: [
        { label: "Restaurants", href: "/industries/restaurants/" },
        { label: "Dental", href: "/industries/dental/" },
        { label: "Lawyers", href: "/industries/lawyers/" },
        { label: "E-Commerce", href: "/industries/ecommerce/" },
        { label: "Contractors", href: "/industries/contractors/" },
        { label: "Real Estate", href: "/industries/real-estate/" },
      ]},
      { label: "Areas", href: "/areas/", children: [
        { label: "Ottawa", href: "/areas/ottawa/" },
        { label: "Kanata", href: "/areas/kanata/" },
        { label: "Barrhaven", href: "/areas/barrhaven/" },
        { label: "Orleans", href: "/areas/orleans/" },
        { label: "Nepean", href: "/areas/nepean/" },
        { label: "Gloucester", href: "/areas/gloucester/" },
        { label: "Gatineau", href: "/areas/gatineau/" },
      ]},
      { label: "Blog", href: "/blog/" },
      { label: "About", href: "/about/" },
      { label: "Contact", href: "/contact/" },
    ],
  },
  footer: {
    description: "Ottawa's trusted web design agency helping small businesses build powerful online presences since 2018.",
    socialLinks: {
      facebook: "https://facebook.com/neonwebagency",
      instagram: "https://instagram.com/neonwebagency",
      linkedin: "https://linkedin.com/company/neonwebagency",
      twitter: "https://twitter.com/neonwebagency",
    },
  },
  schema: {
    type: ["LocalBusiness", "ProfessionalService"] as const,
    geo: { latitude: 45.4215, longitude: -75.6972 },
    areaServed: ["Ottawa", "Kanata", "Barrhaven", "Orleans", "Nepean", "Gloucester", "Gatineau"],
    openingHours: "Mo-Fr 09:00-17:00",
    sameAs: [
      "https://facebook.com/neonwebagency",
      "https://instagram.com/neonwebagency",
      "https://linkedin.com/company/neonwebagency",
      "https://twitter.com/neonwebagency",
    ],
  },
};

export type SiteConfig = typeof siteConfig;
